import type { Metadata } from 'next';
import './globals.css';
import { FC, ReactNode } from 'react';
import HeaderComponent from '@/components/HeaderComponent';

export const metadata: Metadata = {
    title: 'JSON Placeholder Next App',
    description: 'Generated by create next app',
};

interface IProps {
    children: ReactNode;
}

const RootLayout: FC<Readonly<IProps>> = ({children}) => {
    return (
        <html lang="en">
        <body>
        <HeaderComponent />
        {children}
        </body>
        </html>
    );
};

export default RootLayout;